# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c68eda88fd8f8d0f7c3be5fc7970e8668319713fec27633690e3b8201282bb3fc758c99fa2c64c16c57ed81f8e9fe8d17dbe07f1cf337e692dc40c588e2b55d

test:
  secret_key_base: 32aa3c3900610da6fc6867895885bf9160e95ed38516978a26f77aeea41a970494f707a65a1221d524a3072ef05ed6bac5c6aa86a525899a24a888a6973e5488

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
